# Generated by Django 2.2 on 2021-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='added_on',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='added_on',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
